name: read_with_jeel
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  audio_service: 0.18.4
  audioplayers: 0.20.1
  flip_board: ^0.6.1
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety




dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

